
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/spring_cache
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

mybatis:
  configuration:
  #开启驼峰命名法
    map-underscore-to-camel-case: true
debug: false
logging:
  level:
    com.cjk.cache.mapper: debug



#    schema: classpath:schema.sql
